server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
  mongodb:
  url: mongodb://localhost:27018/catalog/
    embedded:
      version: 4.0.2
    data:
      mongodb:
        host: localhost
        database: test
        port: 27017
rabbitmq:
  username: root
  password: root
  host: localhost
  port: 5672
zipkin:
  base-url: http://localhost:9411
  sender:
    type: rabbit
    enabled: true
sleuth:
  sampler:
  probability: 1.0

queue:
  serie:
    name: SerieQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: true
      lease-expiration-duration-in-seconds: 10